#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from mini_l.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 12 "mini_l.y"


	#include <stdlib.h>
	#include <stdio.h>
	#include <string>
	#include <iostream>
	#include <sstream>
	#include <stack>
	#include <vector>
	#include <map>

	using namespace std;

	void yyerror(const char *msg);
	int yylex(void); 

	extern int currLine;
	extern int currPos;

	bool Err = false;
	int t = 0, p = 0, l = 0;
	
	// Intermediate code buffer
	ostringstream buff;
	string s1 = "";
	string s2 = "";

	// Error message string
	string errors = "";

	// Storage stacks
	stack<string> ID;
	stack<string> Var;
	stack<string> Comp;
	stack<string> Index;
	stack<string> Rev;
	stack<int> Label;
	stack<int> Loop;
	stack<int> Pred;

	// Symbol table
	map<string, int> Symbols;

	// Keywords
	static const string Key_words[] = { "_program", "_endprogram", "_array", "_if", "_endif", "_while", "_beginloop", "_continue", "_write", "_or", "_true", "_begin_program", "_integer", "_of", "_then", "_else", "_do", "_endloop", "_read", "_and", "_not", "_false" };

	vector<string> Keywords (Key_words, Key_words + sizeof(Key_words) / sizeof(Key_words[0]));


#line 62 "mini_l.y"
typedef union
{

	int number;
	char *string;

} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	PROGRAM	258
#define	BEGIN_PROGRAM	259
#define	END_PROGRAM	260
#define	INTEGER	261
#define	ARRAY	262
#define	OF	263
#define	IF	264
#define	THEN	265
#define	ENDIF	266
#define	ELSE	267
#define	ELSEIF	268
#define	WHILE	269
#define	DO	270
#define	BEGINLOOP	271
#define	ENDLOOP	272
#define	BREAK	273
#define	CONTINUE	274
#define	EXIT	275
#define	READ	276
#define	WRITE	277
#define	AND	278
#define	OR	279
#define	NOT	280
#define	TRUE	281
#define	FALSE	282
#define	SUB	283
#define	ADD	284
#define	MULT	285
#define	DIV	286
#define	MOD	287
#define	EQ	288
#define	NEQ	289
#define	LT	290
#define	GT	291
#define	LTE	292
#define	GTE	293
#define	SEMICOLON	294
#define	COLON	295
#define	COMMA	296
#define	QUESTION	297
#define	L_BRACKET	298
#define	R_BRACKET	299
#define	L_PAREN	300
#define	R_PAREN	301
#define	ASSIGN	302
#define	NUMBER	303
#define	IDENT	304
#define	NEG	305


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int PROGRAM;
static const int BEGIN_PROGRAM;
static const int END_PROGRAM;
static const int INTEGER;
static const int ARRAY;
static const int OF;
static const int IF;
static const int THEN;
static const int ENDIF;
static const int ELSE;
static const int ELSEIF;
static const int WHILE;
static const int DO;
static const int BEGINLOOP;
static const int ENDLOOP;
static const int BREAK;
static const int CONTINUE;
static const int EXIT;
static const int READ;
static const int WRITE;
static const int AND;
static const int OR;
static const int NOT;
static const int TRUE;
static const int FALSE;
static const int SUB;
static const int ADD;
static const int MULT;
static const int DIV;
static const int MOD;
static const int EQ;
static const int NEQ;
static const int LT;
static const int GT;
static const int LTE;
static const int GTE;
static const int SEMICOLON;
static const int COLON;
static const int COMMA;
static const int QUESTION;
static const int L_BRACKET;
static const int R_BRACKET;
static const int L_PAREN;
static const int R_PAREN;
static const int ASSIGN;
static const int NUMBER;
static const int IDENT;
static const int NEG;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,PROGRAM=258
	,BEGIN_PROGRAM=259
	,END_PROGRAM=260
	,INTEGER=261
	,ARRAY=262
	,OF=263
	,IF=264
	,THEN=265
	,ENDIF=266
	,ELSE=267
	,ELSEIF=268
	,WHILE=269
	,DO=270
	,BEGINLOOP=271
	,ENDLOOP=272
	,BREAK=273
	,CONTINUE=274
	,EXIT=275
	,READ=276
	,WRITE=277
	,AND=278
	,OR=279
	,NOT=280
	,TRUE=281
	,FALSE=282
	,SUB=283
	,ADD=284
	,MULT=285
	,DIV=286
	,MOD=287
	,EQ=288
	,NEQ=289
	,LT=290
	,GT=291
	,LTE=292
	,GTE=293
	,SEMICOLON=294
	,COLON=295
	,COMMA=296
	,QUESTION=297
	,L_BRACKET=298
	,R_BRACKET=299
	,L_PAREN=300
	,R_PAREN=301
	,ASSIGN=302
	,NUMBER=303
	,IDENT=304
	,NEG=305


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::PROGRAM=258;
const int YY_parse_CLASS::BEGIN_PROGRAM=259;
const int YY_parse_CLASS::END_PROGRAM=260;
const int YY_parse_CLASS::INTEGER=261;
const int YY_parse_CLASS::ARRAY=262;
const int YY_parse_CLASS::OF=263;
const int YY_parse_CLASS::IF=264;
const int YY_parse_CLASS::THEN=265;
const int YY_parse_CLASS::ENDIF=266;
const int YY_parse_CLASS::ELSE=267;
const int YY_parse_CLASS::ELSEIF=268;
const int YY_parse_CLASS::WHILE=269;
const int YY_parse_CLASS::DO=270;
const int YY_parse_CLASS::BEGINLOOP=271;
const int YY_parse_CLASS::ENDLOOP=272;
const int YY_parse_CLASS::BREAK=273;
const int YY_parse_CLASS::CONTINUE=274;
const int YY_parse_CLASS::EXIT=275;
const int YY_parse_CLASS::READ=276;
const int YY_parse_CLASS::WRITE=277;
const int YY_parse_CLASS::AND=278;
const int YY_parse_CLASS::OR=279;
const int YY_parse_CLASS::NOT=280;
const int YY_parse_CLASS::TRUE=281;
const int YY_parse_CLASS::FALSE=282;
const int YY_parse_CLASS::SUB=283;
const int YY_parse_CLASS::ADD=284;
const int YY_parse_CLASS::MULT=285;
const int YY_parse_CLASS::DIV=286;
const int YY_parse_CLASS::MOD=287;
const int YY_parse_CLASS::EQ=288;
const int YY_parse_CLASS::NEQ=289;
const int YY_parse_CLASS::LT=290;
const int YY_parse_CLASS::GT=291;
const int YY_parse_CLASS::LTE=292;
const int YY_parse_CLASS::GTE=293;
const int YY_parse_CLASS::SEMICOLON=294;
const int YY_parse_CLASS::COLON=295;
const int YY_parse_CLASS::COMMA=296;
const int YY_parse_CLASS::QUESTION=297;
const int YY_parse_CLASS::L_BRACKET=298;
const int YY_parse_CLASS::R_BRACKET=299;
const int YY_parse_CLASS::L_PAREN=300;
const int YY_parse_CLASS::R_PAREN=301;
const int YY_parse_CLASS::ASSIGN=302;
const int YY_parse_CLASS::NUMBER=303;
const int YY_parse_CLASS::IDENT=304;
const int YY_parse_CLASS::NEG=305;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		199
#define	YYFLAG		-32768
#define	YYNTBASE	51

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 121)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     8,    15,    19,    23,    26,    31,    35,    37,
    43,    44,    48,    56,    62,    69,    72,    75,    77,    79,
    81,    86,    90,    91,    94,    95,    99,   101,   105,   108,
   111,   115,   118,   119,   122,   126,   129,   130,   135,   138,
   141,   146,   150,   152,   154,   158,   160,   162,   164,   166,
   168,   170,   173,   177,   181,   184,   187,   188,   191,   195,
   199,   203,   206,   209,   212,   213,   216,   220,   225,   227,
   229,   233,   235,   240,   242,   244,   246,   248,   250,   252,
   254,   256,   258,   260,   262,   264,   266,   268,   270,   272,
   274,   276,   278,   280,   282,   284,   286,   288,   290,   292,
   294,   296,   298,   300,   302,   304,   306,   308,   310,   312,
   314,   316,   318,   320,   322,   324,   326,   328,   330,   332
};

static const short yyrhs[] = {    52,
     0,    75,    76,    77,    53,    78,     0,     1,    75,    76,
    77,    53,    78,     0,    54,    79,    62,     0,    54,    55,
    77,     0,    55,    77,     0,    56,    81,    57,    89,     0,
    56,    80,    76,     0,    76,     0,    82,    83,    84,    85,
    88,     0,     0,    74,    90,    69,     0,    91,    63,    92,
    62,    59,    60,    93,     0,    96,    63,    97,    62,    98,
     0,    99,    97,    62,    98,    96,    63,     0,   100,    61,
     0,   101,    61,     0,   102,     0,   103,     0,   104,     0,
    59,    94,    63,    62,     0,    94,    63,    62,     0,     0,
    95,    62,     0,     0,    61,    80,    74,     0,    74,     0,
    62,    58,    77,     0,    58,    77,     0,    65,    64,     0,
    64,   105,    65,     0,   105,    65,     0,     0,    67,    66,
     0,    66,   106,    67,     0,   106,    67,     0,     0,   107,
    69,    68,    69,     0,   107,   108,     0,   107,   109,     0,
   107,    86,    63,    87,     0,    69,    68,    69,     0,   108,
     0,   109,     0,    86,    63,    87,     0,   110,     0,   111,
     0,   112,     0,   113,     0,   114,     0,   115,     0,    71,
    70,     0,    70,   116,    71,     0,    70,   117,    71,     0,
   116,    71,     0,   117,    71,     0,     0,    73,    72,     0,
    72,   118,    73,     0,    72,   119,    73,     0,    72,   120,
    73,     0,   118,    73,     0,   119,    73,     0,   120,    73,
     0,     0,   117,    74,     0,   117,    84,    74,     0,   117,
    86,    69,    87,     0,    74,     0,    84,     0,    86,    69,
    87,     0,    76,     0,    76,    83,    69,    85,     0,     3,
     0,    49,     0,    39,     0,     5,     0,     4,     0,    41,
     0,    40,     0,     7,     0,    43,     0,    48,     0,    44,
     0,    45,     0,    46,     0,     8,     0,     6,     0,    47,
     0,    42,     0,     9,     0,    10,     0,    11,     0,    13,
     0,    12,     0,    14,     0,    16,     0,    17,     0,    15,
     0,    21,     0,    22,     0,    18,     0,    19,     0,    20,
     0,    24,     0,    23,     0,    25,     0,    26,     0,    27,
     0,    33,     0,    34,     0,    35,     0,    36,     0,    37,
     0,    38,     0,    29,     0,    28,     0,    30,     0,    31,
     0,    32,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   108,   113,   130,   136,   142,   144,   150,   162,   164,   183,
   204,   208,   240,   242,   244,   246,   248,   250,   252,   254,
   260,   262,   264,   270,   272,   278,   280,   286,   288,   294,
   300,   302,   304,   310,   316,   318,   320,   326,   328,   330,
   332,   334,   336,   338,   340,   346,   352,   358,   364,   370,
   376,   386,   392,   394,   396,   398,   400,   406,   412,   414,
   416,   418,   420,   422,   424,   430,   432,   434,   436,   438,
   440,   446,   448,   454,   460,   495,   501,   507,   513,   519,
   523,   529,   535,   541,   547,   553,   557,   561,   567,   573,
   579,   585,   599,   610,   616,   631,   645,   653,   659,   665,
   671,   679,   685,   694,   700,   706,   712,   718,   724,   730,
   736,   742,   748,   754,   760,   764,   770,   776,   782,   788
};

static const char * const yytname[] = {   "$","error","$illegal.","PROGRAM",
"BEGIN_PROGRAM","END_PROGRAM","INTEGER","ARRAY","OF","IF","THEN","ENDIF","ELSE",
"ELSEIF","WHILE","DO","BEGINLOOP","ENDLOOP","BREAK","CONTINUE","EXIT","READ",
"WRITE","AND","OR","NOT","TRUE","FALSE","SUB","ADD","MULT","DIV","MOD","EQ",
"NEQ","LT","GT","LTE","GTE","SEMICOLON","COLON","COMMA","QUESTION","L_BRACKET",
"R_BRACKET","L_PAREN","R_PAREN","ASSIGN","NUMBER","IDENT","NEG","start","program_start",
"block","declaration_list","declaration","identifier_list","optional_array",
"statement","optional_elseif","optional_else","var_list","statement_list","bool_exp",
"relation_and_exp_list","relation_and_exp","relation_exp_list","relation_exp",
"comp","expression","multiplicative_exp_list","multiplicative_exp","term_list",
"term","var","program","identifier","semicolon","end_program","begin_program",
"comma","colon","array","l_bracket","number","r_bracket","l_paren","r_paren",
"of","integer","assign","if","then","end_if","elseif","else","while","begin_loop",
"end_loop","do","read","write","break","continue","exit","or","and","not","true",
"false","equal_to","not_equal_to","less_than","greater_than","less_than_or_equal_to",
"greater_than_or_equal_to","add","sub","multiply","divide","mod","mod"
};
#endif

static const short yyr1[] = {     0,
    51,    52,    52,    53,    54,    54,    55,    56,    56,    57,
    57,    58,    58,    58,    58,    58,    58,    58,    58,    58,
    59,    59,    59,    60,    60,    61,    61,    62,    62,    63,
    64,    64,    64,    65,    66,    66,    66,    67,    67,    67,
    67,    67,    67,    67,    67,    68,    68,    68,    68,    68,
    68,    69,    70,    70,    70,    70,    70,    71,    72,    72,
    72,    72,    72,    72,    72,    73,    73,    73,    73,    73,
    73,    74,    74,    75,    76,    77,    78,    79,    80,    81,
    82,    83,    84,    85,    86,    87,    88,    89,    90,    -1,
    91,    92,    93,    94,    95,    96,    97,    98,    99,   100,
   101,   102,   103,   104,   105,   106,   107,   108,   109,   110,
   111,   112,   113,   114,   115,   116,   117,   118,   119,   120
};

static const short yyr2[] = {     0,
     1,     5,     6,     3,     3,     2,     4,     3,     1,     5,
     0,     3,     7,     5,     6,     2,     2,     1,     1,     1,
     4,     3,     0,     2,     0,     3,     1,     3,     2,     2,
     3,     2,     0,     2,     3,     2,     0,     4,     2,     2,
     4,     3,     1,     1,     3,     1,     1,     1,     1,     1,
     1,     2,     3,     3,     2,     2,     0,     2,     3,     3,
     3,     2,     2,     2,     0,     2,     3,     4,     1,     1,
     3,     1,     4,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
     0,    74,     1,     0,     0,    75,     0,     0,    76,     0,
     0,     0,     0,     0,     0,     9,     0,    77,     2,    78,
     0,     0,     6,    80,    79,     0,    11,     3,     5,    91,
    96,    99,   102,   103,   104,   100,   101,     0,     4,     0,
    72,     0,     0,     0,     0,     0,    18,    19,    20,     8,
    81,     0,     0,    29,     0,    89,     0,    82,     0,   107,
   108,   109,   117,    85,    83,     0,    33,    37,     0,    57,
    65,    69,    70,     0,     0,    43,    44,     0,     0,    97,
     0,    16,    27,    17,    88,     7,     0,    28,    12,     0,
     0,    92,     0,   105,    30,     0,   106,    34,     0,   110,
   111,   112,   113,   114,   115,     0,    46,    47,    48,    49,
    50,    51,   116,    52,     0,     0,   118,   119,   120,    58,
     0,     0,     0,     0,     0,     0,     0,    39,    40,    66,
     0,     0,     0,     0,     0,     0,     0,    84,    73,    23,
     0,    32,     0,    36,    42,     0,     0,    55,    56,     0,
     0,     0,    62,    63,    64,    86,    45,    71,     0,     0,
    67,     0,     0,    98,     0,    26,     0,    94,    25,     0,
    31,    35,    53,    54,    59,    60,    61,    38,    41,    68,
    14,     0,    87,    10,    95,     0,     0,     0,     0,    15,
    93,    13,     0,    24,    22,    21,     0,     0,     0
};

static const short yydefgoto[] = {   197,
     3,    12,    13,    14,    15,    52,    38,   169,   186,    82,
    39,    66,    95,    67,    98,    68,   106,    69,   114,    70,
   120,    71,    72,     4,    41,    10,    19,    22,   135,    27,
    53,    59,    73,   139,    90,   158,   184,    86,    57,    42,
    93,   192,   170,   188,    43,    81,   165,    44,    45,    46,
    47,    48,    49,    96,    99,    75,    76,    77,   107,   108,
   109,   110,   111,   112,   115,    78,   121,   122,   123
};

static const short yypact[] = {   105,
    15,-32768,-32768,   -27,   -27,-32768,     2,     2,-32768,   -27,
   -27,    44,     1,     2,   -26,-32768,    44,-32768,-32768,-32768,
     2,   161,-32768,-32768,-32768,   -27,    45,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,     2,   161,    11,
    23,    20,    20,    51,   -27,   -27,-32768,-32768,-32768,-32768,
-32768,    67,    23,-32768,     2,-32768,    75,-32768,    75,-32768,
-32768,-32768,-32768,-32768,-32768,    80,    65,    72,   154,     8,
    54,-32768,-32768,    20,   158,-32768,-32768,   -17,    51,-32768,
   161,    73,-32768,    73,-32768,-32768,    71,-32768,-32768,    75,
    78,-32768,   161,-32768,    65,    20,-32768,    72,    20,-32768,
-32768,-32768,-32768,-32768,-32768,    75,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,     8,    75,    75,-32768,-32768,-32768,    54,
    75,    75,    75,    69,   102,   154,    20,-32768,-32768,-32768,
   -27,    75,   161,    61,   -27,    78,    69,-32768,-32768,    79,
    20,-32768,    20,-32768,-32768,    75,    75,-32768,-32768,    75,
    75,    75,-32768,-32768,-32768,-32768,-32768,-32768,    75,    69,
-32768,    69,    61,-32768,   112,-32768,   119,-32768,    17,    20,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,    20,-32768,-32768,-32768,   118,    20,   161,   161,-32768,
-32768,-32768,   161,   161,   161,   161,   145,   153,-32768
};

static const short yypgoto[] = {-32768,
-32768,   143,-32768,   142,-32768,-32768,   -38,-32768,-32768,   113,
   -72,   -40,-32768,   -88,-32768,   -89,    37,   -55,-32768,  -103,
-32768,    10,   -22,   163,   139,    19,   151,-32768,   162,-32768,
-32768,   116,   -62,    42,   -36,   -98,-32768,-32768,-32768,-32768,
-32768,-32768,    24,-32768,    29,   117,    32,-32768,-32768,-32768,
-32768,-32768,-32768,   103,    99,-32768,   124,   125,-32768,-32768,
-32768,-32768,-32768,-32768,    87,   -59,    82,    84,    85
};


#define	YYLAST		210


static const short yytable[] = {    40,
    55,    89,    79,    91,    20,    74,    74,   142,   134,   144,
   116,   148,   149,    24,    25,   131,    40,     2,   125,   126,
   140,     6,    83,    83,   136,   157,    11,    64,   185,   168,
    65,     6,    23,   124,   137,    63,   113,    74,   127,    29,
     9,   132,   173,   174,    60,    61,    62,    63,    18,     6,
   145,    51,   171,   172,   147,   130,    54,    56,    40,    74,
   163,   179,    74,   180,    64,    58,    80,    65,     6,    30,
    40,   125,    85,    88,    31,    32,   162,   164,    33,    34,
    35,    36,    37,   117,   118,   119,   160,    30,    94,    92,
    74,   168,    31,    32,    97,    55,    33,    34,    35,    36,
    37,    55,    63,   178,    74,     1,    74,     2,   161,     6,
    40,    40,   166,    25,   156,   194,   195,    40,    65,    64,
   196,   138,    65,     6,    55,    31,   183,     6,   191,   189,
   153,   154,   155,    74,   100,   101,   102,   103,   104,   105,
    40,   190,     7,     8,   198,    74,   193,   156,    16,    16,
    74,    16,   199,    17,    21,    55,    55,    55,    84,   175,
   176,   177,   159,     5,    50,    40,    40,    28,    87,    30,
    40,    40,    40,    40,    31,    32,    26,   167,    33,    34,
    35,    36,    37,    61,    62,    63,   100,   101,   102,   103,
   104,   105,   187,   182,   181,   133,   143,   141,   128,   129,
   146,   150,    64,   151,   152,    65,     6,     0,     0,     6
};

static const short yycheck[] = {    22,
    39,    57,    43,    59,     4,    42,    43,    96,    81,    99,
    70,   115,   116,    40,    41,    78,    39,     3,    74,    75,
    93,    49,    45,    46,    87,   124,     8,    45,    12,    13,
    48,    49,    14,    74,    90,    28,    29,    74,    75,    21,
    39,    78,   146,   147,    25,    26,    27,    28,     5,    49,
   106,     7,   141,   143,   114,    78,    38,    47,    81,    96,
   133,   160,    99,   162,    45,    43,    16,    48,    49,     9,
    93,   127,     6,    55,    14,    15,   132,    17,    18,    19,
    20,    21,    22,    30,    31,    32,   127,     9,    24,    10,
   127,    13,    14,    15,    23,   134,    18,    19,    20,    21,
    22,   140,    28,   159,   141,     1,   143,     3,   131,    49,
   133,   134,   135,    41,    46,   188,   189,   140,    48,    45,
   193,    44,    48,    49,   163,    14,     8,    49,    11,   170,
   121,   122,   123,   170,    33,    34,    35,    36,    37,    38,
   163,   182,     4,     5,     0,   182,   187,    46,    10,    11,
   187,    13,     0,    11,    13,   194,   195,   196,    46,   150,
   151,   152,   126,     1,    26,   188,   189,    17,    53,     9,
   193,   194,   195,   196,    14,    15,    15,   136,    18,    19,
    20,    21,    22,    26,    27,    28,    33,    34,    35,    36,
    37,    38,   169,   165,   163,    79,    98,    95,    75,    75,
   114,   120,    45,   120,   120,    48,    49,    -1,    -1,    49
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 108 "mini_l.y"
{
	buff << ": START\n";
;
    break;}
case 2:
#line 113 "mini_l.y"
{
		if(!Err) 
		{
			for(int i = 0; i < t; i++)
			{
				cout << "\t. t" << i << endl;
			}

			for(int j = 0; j < p; j ++)
			{
				cout << "\t. p" << j << endl;
			}

			cout << buff.str();
		}
;
    break;}
case 7:
#line 150 "mini_l.y"
{
	while(!ID.empty()) 
	{
		buff << "\t. " << ID.top() << endl;
		ID.pop();
	}
;
    break;}
case 9:
#line 164 "mini_l.y"
{
	// Error check
	string id = "_" + string(yyvsp[0].string);
	map<string, int>::iterator i = Symbols.find(id);

	if (i != Symbols.end())
	{
		errors = "Error: " + id + " has been previously defined";
		yyerror(errors.c_str());
	}

	Symbols[id] = -1;
	ID.push(id);
;
    break;}
case 10:
#line 183 "mini_l.y"
{
	int num = yyvsp[-2].number;

    //Error check
	if(num <= 0) 
	{	
		errors = "Error: Declaring array of invalid size.";
		yyerror(errors.c_str());	
	}

	while(!ID.empty())
	{
		buff << "\t.[] " << ID.top() << ", " << num << endl;

		string id = ID.top();

		Symbols[id] = num;
		ID.pop();
	} 
;
    break;}
case 12:
#line 208 "mini_l.y"
{

	/*s2 = Var.top();
	if(Index.top() != "-1")
	{
		ostringstream convert;
		convert << t;
		buff << "\t=[] t" << t << ", " << s2 << ", " << Index.top() << endl;

		s2 = "t" + convert.str();
		t++;
	}

	Var.pop();
	Index.pop();
	s1 = Var.top();

	if(Index.top() != "-1")
	{
		buff << "\t[]= " << s1 << ", " << Index.top() << ", " << s2 << endl;
	}

	else
	{
		buff << "\t= " << s1 << ", " << s2 << endl;
	}

	Var.pop();
	Index.pop(); */
 
;
    break;}
case 46:
#line 346 "mini_l.y"
{

	Comp.push("==");

;
    break;}
case 47:
#line 352 "mini_l.y"
{

	Comp.push("!=");

;
    break;}
case 48:
#line 358 "mini_l.y"
{

	Comp.push("<");

;
    break;}
case 49:
#line 364 "mini_l.y"
{

	Comp.push(">");

;
    break;}
case 50:
#line 370 "mini_l.y"
{

	Comp.push("<=");

;
    break;}
case 51:
#line 376 "mini_l.y"
{

	Comp.push(">=");

;
    break;}
case 75:
#line 460 "mini_l.y"
{

	// Search symbol table for identifier
	string id = "_" + string(yyvsp[0].string);
	map <string, int>::iterator i = Symbols.find(id);

	// Error check
	if (i != Symbols.end())
	{
		errors = "Error: " + id + " was previously defined";
		yyerror(errors.c_str());
	}

	bool keybool = false;
	int size = Keywords.size();

	for(int j = 0; j < size; j++)
	{
		(id == Keywords[j]) ? keybool = true : keybool;	
	}
	
	if(keybool == true)
	{
		errors = "Error: " + id + " has been defined as a keyword and cannot be used";
		yyerror(errors.c_str());
	}

	Var.push(id);

;
    break;}
case 92:
#line 586 "mini_l.y"
{
	int s2 = Pred.top();
	Pred.pop();

	buff << "\t?:= L" << l << ", p" << s2 << endl;
	Label.push(l);
	l++;	
;
    break;}
case 93:
#line 599 "mini_l.y"
{

	buff << ": L" << Label.top() << endl;
	Label.pop();

;
    break;}
case 95:
#line 616 "mini_l.y"
{

	buff << "\t:= L" << l << endl;
	buff << ": L" << Label.top() << endl;
	Label.pop();
	Label.push(l);

	l++;

;
    break;}
case 96:
#line 631 "mini_l.y"
{

	buff << ": L" << l << endl;

	Loop.push(l);
	Label.push(l);
	++l;
	
;
    break;}
case 97:
#line 645 "mini_l.y"
{
	int t = Pred.top();
;
    break;}
case 103:
#line 685 "mini_l.y"
{
	if(!Loop.empty())
	{
		buff << "\t:= L" << Loop.top() << endl;
	}
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 794 "mini_l.y"


int main(int argc, char **argv) {
   if (argc > 1) 
   {

      if (freopen(argv[1], "r", stdin) == NULL)
      {

		 printf("syntax: %s filename\n", argv[0]);

      }//end if

   }//end if

   yyparse(); // Calls yylex() for tokens.

   return 0;

}

void yyerror(const char *msg) {

   printf("** Line %d %s\n", currLine, msg);
}
